// Package number_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package number_manager

// Defines values for AvailableNumberFeature.
const (
	AvailableNumberFeatureEmergency AvailableNumberFeature = "emergency"
	AvailableNumberFeatureFax       AvailableNumberFeature = "fax"
	AvailableNumberFeatureMMS       AvailableNumberFeature = "mms"
	AvailableNumberFeatureSMS       AvailableNumberFeature = "sms"
	AvailableNumberFeatureVoice     AvailableNumberFeature = "voice"
)

// Defines values for NumberProviderName.
const (
	ProviderNameMessagebird NumberProviderName = "messagebird"
	ProviderNameTelnyx      NumberProviderName = "telnyx"
	ProviderNameTwilio      NumberProviderName = "twilio"
)

// Defines values for NumberStatus.
const (
	StatusActive  NumberStatus = "active"
	StatusDeleted NumberStatus = "deleted"
)

// AvailableNumber defines model for AvailableNumber.
type AvailableNumber struct {
	// Country The country where the number is available.
	Country *string `json:"country,omitempty"`

	// Features The list of features supported by the number.
	Features *[]AvailableNumberFeature `json:"features,omitempty"`

	// Number The available phone number.
	Number *string `json:"number,omitempty"`

	// PostalCode The postal code associated with the number.
	PostalCode *string `json:"postal_code,omitempty"`

	// Region The region within the country.
	Region *string `json:"region,omitempty"`
}

// AvailableNumberFeature A feature supported by the phone number.
type AvailableNumberFeature string

// Number defines model for Number.
type Number struct {
	// CallFlowId The ID of the associated call flow.
	CallFlowId *string `json:"call_flow_id,omitempty"`

	// CustomerId The customer ID associated with the number.
	CustomerId *string `json:"customer_id,omitempty"`

	// Detail Additional details about the number.
	Detail *string `json:"detail,omitempty"`

	// EmergencyEnabled Whether emergency services are enabled for the number.
	EmergencyEnabled *bool `json:"emergency_enabled,omitempty"`

	// Id The unique identifier for the number.
	Id *string `json:"id,omitempty"`

	// MessageFlowId The ID of the associated message flow.
	MessageFlowId *string `json:"message_flow_id,omitempty"`

	// Name The name of the number.
	Name *string `json:"name,omitempty"`

	// Number The phone number.
	Number *string `json:"number,omitempty"`

	// Status The status of the number.
	Status *NumberStatus `json:"status,omitempty"`

	// T38Enabled Whether T38 is enabled for the number.
	T38Enabled *bool `json:"t38_enabled,omitempty"`

	// TmCreate The timestamp of when the number was created.
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete The timestamp of when the number was deleted.
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmPurchase The timestamp of when the number was purchased.
	TmPurchase *string `json:"tm_purchase,omitempty"`

	// TmRenew The timestamp of when the number was renewed.
	TmRenew *string `json:"tm_renew,omitempty"`

	// TmUpdate The timestamp of when the number was last updated.
	TmUpdate *string `json:"tm_update,omitempty"`
}

// NumberProviderName The provider name for the number.
type NumberProviderName string

// NumberStatus The status of the number.
type NumberStatus string
