// Package number_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package number_manager

// Defines values for AvailableNumberFeature.
const (
	AvailableNumberFeatureEmergency AvailableNumberFeature = "emergency"
	AvailableNumberFeatureFax       AvailableNumberFeature = "fax"
	AvailableNumberFeatureMMS       AvailableNumberFeature = "mms"
	AvailableNumberFeatureSMS       AvailableNumberFeature = "sms"
	AvailableNumberFeatureVoice     AvailableNumberFeature = "voice"
)

// AvailableNumber defines model for AvailableNumber.
type AvailableNumber struct {
	// Country The country where the number is available.
	Country *string `json:"country,omitempty"`

	// Features The list of features supported by the number.
	Features *[]AvailableNumberFeature `json:"features,omitempty"`

	// Number The available phone number.
	Number *string `json:"number,omitempty"`

	// PostalCode The postal code associated with the number.
	PostalCode *string `json:"postal_code,omitempty"`

	// Region The region within the country.
	Region *string `json:"region,omitempty"`
}

// AvailableNumberFeature A feature supported by the phone number.
type AvailableNumberFeature string
