// Package customer_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package customer_manager

import (
	"time"
)

// Accesskey defines model for Accesskey.
type Accesskey struct {
	CustomerId *string    `json:"customer_id,omitempty"`
	Detail     *string    `json:"detail,omitempty"`
	Id         *string    `json:"id,omitempty"`
	Name       *string    `json:"name,omitempty"`
	TmCreate   *time.Time `json:"tm_create,omitempty"`
	TmDelete   *time.Time `json:"tm_delete,omitempty"`
	TmExpire   *time.Time `json:"tm_expire,omitempty"`
	TmUpdate   *time.Time `json:"tm_update,omitempty"`
	Token      *string    `json:"token,omitempty"`
}
