// Package registrar_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package registrar_manager

// Defines values for AuthType.
const (
	AuthTypeBasic AuthType = "basic"
	AuthTypeIP    AuthType = "ip"
)

// AuthType Defines the authentication type. Can be 'basic' or 'ip'.
type AuthType string

// Extension defines model for Extension.
type Extension struct {
	CustomerId *string `json:"customer_id,omitempty"`
	Detail     *string `json:"detail,omitempty"`

	// DomainName Domain name, same as the customer_id, used by Kamailio's INVITE validation
	DomainName *string `json:"domain_name,omitempty"`
	Extension  *string `json:"extension,omitempty"`
	Id         *string `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Password   *string `json:"password,omitempty"`

	// TmCreate Timestamp when the extension was created
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the extension was deleted
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the extension was last updated
	TmUpdate *string `json:"tm_update,omitempty"`

	// Username Username, same as the Extension, used by Kamailio's INVITE validation
	Username *string `json:"username,omitempty"`
}

// Trunk defines model for Trunk.
type Trunk struct {
	AllowedIps *[]string   `json:"allowed_ips,omitempty"`
	AuthTypes  *[]AuthType `json:"auth_types,omitempty"`
	CustomerId *string     `json:"customer_id,omitempty"`
	Detail     *string     `json:"detail,omitempty"`
	DomainName *string     `json:"domain_name,omitempty"`
	Id         *string     `json:"id,omitempty"`
	Name       *string     `json:"name,omitempty"`
	Password   *string     `json:"password,omitempty"`

	// TmCreate Timestamp when the trunk was created
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the trunk was deleted
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the trunk was last updated
	TmUpdate *string `json:"tm_update,omitempty"`
	Username *string `json:"username,omitempty"`
}
