// Package conversation_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package conversation_manager

import (
	externalRef1 "testoapi/gens/models/common"
)

// Defines values for AccountType.
const (
	AccountTypeLine AccountType = "line"
	AccountTypeSMS  AccountType = "sms"
)

// Defines values for ConversationreferenceType.
const (
	ConversationreferenceTypeLine    ConversationreferenceType = "line"
	ConversationreferenceTypeMessage ConversationreferenceType = "message"
	ConversationreferenceTypeNone    ConversationreferenceType = ""
)

// Defines values for MediaType.
const (
	MediaTypeAudio    MediaType = "audio"
	MediaTypeFile     MediaType = "file"
	MediaTypeFlex     MediaType = "flex"
	MediaTypeImage    MediaType = "image"
	MediaTypeImagemap MediaType = "imagemap"
	MediaTypeLocation MediaType = "location"
	MediaTypeSticker  MediaType = "sticker"
	MediaTypeTemplate MediaType = "template"
	MediaTypeVideo    MediaType = "video"
)

// Defines values for MessageDirection.
const (
	MessageDirectionIncoming MessageDirection = "incoming"
	MessageDirectionOutgoing MessageDirection = "outgoing"
)

// Defines values for MessageStatus.
const (
	MessageStatusFailed   MessageStatus = "failed"
	MessageStatusReceived MessageStatus = "received"
	MessageStatusSending  MessageStatus = "sending"
	MessageStatusSent     MessageStatus = "sent"
)

// Defines values for MessagereferenceType.
const (
	MessagereferenceTypeCall     MessagereferenceType = "call"
	MessagereferenceTypeCampaign MessagereferenceType = "campaign"
	MessagereferenceTypeNone     MessagereferenceType = "none"
)

// Account defines model for Account.
type Account struct {
	// CustomerId Unique identifier of the associated customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Detail Detailed information about the account.
	Detail *string `json:"detail,omitempty"`

	// Id Unique identifier for the account.
	Id *string `json:"id,omitempty"`

	// Name Name of the account.
	Name *string `json:"name,omitempty"`

	// Secret Secret associated with the account.
	Secret *string `json:"secret,omitempty"`

	// TmCreate Timestamp when the account was created.
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the account was deleted.
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the account was last updated.
	TmUpdate *string `json:"tm_update,omitempty"`

	// Token Token, usually an API token, associated with the account.
	Token *string `json:"token,omitempty"`

	// Type Type of the account.
	Type *AccountType `json:"type,omitempty"`
}

// AccountType Type of the account.
type AccountType string

// Conversation defines model for Conversation.
type Conversation struct {
	// AccountId Unique identifier of the associated account.
	AccountId *string `json:"account_id,omitempty"`

	// CustomerId Unique identifier of the associated customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Detail Detailed information about the conversation.
	Detail *string `json:"detail,omitempty"`

	// Id Unique identifier for the conversation.
	Id *string `json:"id,omitempty"`

	// Name Name of the conversation.
	Name *string `json:"name,omitempty"`

	// Participants List of participants in the conversation.
	Participants *[]externalRef1.Address `json:"participants,omitempty"`

	// ReferenceId Unique identifier for the reference (e.g., message ID, line ID).
	ReferenceId *string `json:"reference_id,omitempty"`

	// ReferenceType Type of the reference for the conversation.
	ReferenceType *ConversationreferenceType `json:"reference_type,omitempty"`

	// Source Contains source or destination detail info.
	Source *externalRef1.Address `json:"source,omitempty"`

	// TmCreate Timestamp when the conversation was created.
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the conversation was deleted.
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the conversation was last updated.
	TmUpdate *string `json:"tm_update,omitempty"`
}

// ConversationreferenceType Type of the reference for the conversation.
type ConversationreferenceType string

// Media defines model for Media.
type Media struct {
	// CustomerId Unique identifier of the associated customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Filename Filename of the media.
	Filename *string `json:"filename,omitempty"`

	// Id Unique identifier for the media.
	Id *string `json:"id,omitempty"`

	// TmCreate Timestamp when the media was created.
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the media was deleted.
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the media was last updated.
	TmUpdate *string `json:"tm_update,omitempty"`

	// Type Type of the media.
	Type *MediaType `json:"type,omitempty"`
}

// MediaType Type of the media.
type MediaType string

// Message defines model for Message.
type Message struct {
	// ConversationId Unique identifier of the conversation.
	ConversationId *string `json:"conversation_id,omitempty"`

	// CustomerId Unique identifier of the associated customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Direction Direction of the message (incoming or outgoing).
	Direction *MessageDirection `json:"direction,omitempty"`

	// Id Unique identifier for the message.
	Id *string `json:"id,omitempty"`

	// Medias List of media associated with the message.
	Medias *[]Media `json:"medias,omitempty"`

	// ReferenceId The reference ID for the message (e.g., related call ID).
	ReferenceId *string `json:"reference_id,omitempty"`

	// ReferenceType Type of reference associated with the message (e.g., call, campaign).
	ReferenceType *MessagereferenceType `json:"reference_type,omitempty"`

	// Source Contains source or destination detail info.
	Source *externalRef1.Address `json:"source,omitempty"`

	// Status Status of the message.
	Status *MessageStatus `json:"status,omitempty"`

	// Text The message content.
	Text *string `json:"text,omitempty"`

	// TmCreate Timestamp when the message was created.
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the message was deleted.
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the message was last updated.
	TmUpdate *string `json:"tm_update,omitempty"`
}

// MessageDirection Direction of the message (incoming or outgoing).
type MessageDirection string

// MessageStatus Status of the message.
type MessageStatus string

// MessagereferenceType Type of reference associated with the message (e.g., call, campaign).
type MessagereferenceType string
