// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package common

// Defines values for AddressType.
const (
	AddressTypeAgent      AddressType = "agent"
	AddressTypeConference AddressType = "conference"
	AddressTypeExtension  AddressType = "extension"
	AddressTypeLine       AddressType = "line"
	AddressTypeNone       AddressType = ""
	AddressTypeSIP        AddressType = "sip"
	AddressTypeTel        AddressType = "tel"
)

// Address Contains source or destination detail info.
type Address struct {
	// Detail Detail description.
	Detail *string `json:"detail,omitempty"`

	// Name Name.
	Name *string `json:"name,omitempty"`

	// Target Address endpoint.
	Target *string `json:"target,omitempty"`

	// TargetName Address's name.
	TargetName *string `json:"target_name,omitempty"`

	// Type Type of address.
	Type *AddressType `json:"type,omitempty"`
}

// AddressType Type of address.
type AddressType string

// Pagination defines model for Pagination.
type Pagination struct {
	// NextPageToken The token for next pagination.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string
