// Package conference_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package conference_manager

import (
	externalRef2 "testoapi/gens/models/flow_manager"
)

// Defines values for ConferenceStatus.
const (
	ConferenceStatusProgressing ConferenceStatus = "progressing"
	ConferenceStatusStarting    ConferenceStatus = "starting"
	ConferenceStatusTerminated  ConferenceStatus = "terminated"
	ConferenceStatusTerminating ConferenceStatus = "terminating"
)

// Defines values for ConferenceType.
const (
	ConferenceTypeConference ConferenceType = "conference"
	ConferenceTypeConnect    ConferenceType = "connect"
	ConferenceTypeNone       ConferenceType = ""
	ConferenceTypeQueue      ConferenceType = "queue"
)

// Defines values for ConferencecallStatus.
const (
	ConferencecallStatusJoined  ConferencecallStatus = "joined"
	ConferencecallStatusJoining ConferencecallStatus = "joining"
	ConferencecallStatusLeaved  ConferencecallStatus = "leaved"
	ConferencecallStatusLeaving ConferencecallStatus = "leaving"
)

// Defines values for ConferencecallreferenceType.
const (
	ReferenceTypeCall ConferencecallreferenceType = "call"
)

// Conference defines model for Conference.
type Conference struct {
	// ConferencecallIds List of associated conference call IDs.
	ConferencecallIds *[]string `json:"conferencecall_ids,omitempty"`

	// CustomerId Unique identifier of the associated customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Data Custom data associated with the conference.
	Data *map[string]interface{} `json:"data,omitempty"`

	// Detail Detailed information about the conference.
	Detail *string `json:"detail,omitempty"`

	// Id Unique identifier for the conference.
	Id *string `json:"id,omitempty"`

	// Name Name of the conference.
	Name *string `json:"name,omitempty"`

	// PostActions Post-actions to execute after the conference ends.
	PostActions *[]externalRef2.Action `json:"post_actions,omitempty"`

	// PreActions Pre-actions to execute before the conference starts.
	PreActions *[]externalRef2.Action `json:"pre_actions,omitempty"`

	// RecordingId ID of the main recording associated with the conference.
	RecordingId *string `json:"recording_id,omitempty"`

	// RecordingIds List of associated recording IDs.
	RecordingIds *[]string `json:"recording_ids,omitempty"`

	// Status Status of the conference.
	Status *ConferenceStatus `json:"status,omitempty"`

	// Timeout Timeout for the conference in seconds.
	Timeout *int32 `json:"timeout,omitempty"`

	// TmCreate Timestamp when the conference was created.
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the conference was deleted.
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmEnd Timestamp when the conference ended.
	TmEnd *string `json:"tm_end,omitempty"`

	// TmUpdate Timestamp when the conference was last updated.
	TmUpdate *string `json:"tm_update,omitempty"`

	// TranscribeId ID of the main transcription associated with the conference.
	TranscribeId *string `json:"transcribe_id,omitempty"`

	// TranscribeIds List of associated transcription IDs.
	TranscribeIds *[]string `json:"transcribe_ids,omitempty"`

	// Type Types of conferences.
	Type *ConferenceType `json:"type,omitempty"`
}

// ConferenceStatus Status of the conference.
type ConferenceStatus string

// ConferenceType Types of conferences.
type ConferenceType string

// Conferencecall defines model for Conferencecall.
type Conferencecall struct {
	// ConferenceId Unique identifier of the associated conference.
	ConferenceId *string `json:"conference_id,omitempty"`

	// CustomerId Unique identifier of the associated customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Id Unique identifier for the conference call.
	Id *string `json:"id,omitempty"`

	// ReferenceId Unique identifier of the reference (e.g., call ID).
	ReferenceId *string `json:"reference_id,omitempty"`

	// ReferenceType Type of the reference associated with the conference call.
	ReferenceType *ConferencecallreferenceType `json:"reference_type,omitempty"`

	// Status Status of the conference call.
	Status *ConferencecallStatus `json:"status,omitempty"`

	// TmCreate Timestamp when the conference call was created.
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the conference call was deleted.
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the conference call was last updated.
	TmUpdate *string `json:"tm_update,omitempty"`
}

// ConferencecallStatus Status of the conference call.
type ConferencecallStatus string

// ConferencecallreferenceType Type of the reference associated with the conference call.
type ConferencecallreferenceType string
