// Package flow_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package flow_manager

import (
	"time"
)

// Defines values for ActiveflowReferenceType.
const (
	ActiveflowTypeCall    ActiveflowReferenceType = "call"
	ActiveflowTypeMessage ActiveflowReferenceType = "message"
	ActiveflowTypeNone    ActiveflowReferenceType = ""
)

// Defines values for ActiveflowStatus.
const (
	ActiveflowStatusEnded   ActiveflowStatus = "ended"
	ActiveflowStatusNone    ActiveflowStatus = ""
	ActiveflowStatusRunning ActiveflowStatus = "running"
)

// Action defines model for Action.
type Action struct {
	// Id The unique identifier
	Id string `json:"id"`

	// NextId The identifier of the next item
	NextId *string `json:"next_id,omitempty"`

	// Option Additional options
	Option *map[string]interface{} `json:"option,omitempty"`

	// TmExecute Timestamp or time to execute
	TmExecute *string `json:"tm_execute,omitempty"`

	// Type The type of the object
	Type string `json:"type"`
}

// Activeflow defines model for Activeflow.
type Activeflow struct {
	CurrentAction *Action `json:"current_action,omitempty"`

	// CustomerId ID of the customer associated with the flow.
	CustomerId *string `json:"customer_id,omitempty"`

	// ExecutedActions List of actions that have been executed.
	ExecutedActions *[]Action `json:"executed_actions,omitempty"`

	// FlowId ID of the flow definition.
	FlowId *string `json:"flow_id,omitempty"`

	// ForwardActionId ID of the next action to be executed.
	ForwardActionId *string `json:"forward_action_id,omitempty"`

	// Id Unique identifier for the activeflow.
	Id *string `json:"id,omitempty"`

	// ReferenceId ID of the reference object.
	ReferenceId *string `json:"reference_id,omitempty"`

	// ReferenceType Reference type of activeflow.
	ReferenceType *ActiveflowReferenceType `json:"reference_type,omitempty"`

	// Status Status of the activeflow.
	Status *ActiveflowStatus `json:"status,omitempty"`

	// TmCreate Timestamp when the flow was created.
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the flow was deleted.
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the flow was last updated.
	TmUpdate *time.Time `json:"tm_update,omitempty"`
}

// ActiveflowReferenceType Reference type of activeflow.
type ActiveflowReferenceType string

// ActiveflowStatus Status of the activeflow.
type ActiveflowStatus string
