// Package transcribe_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package transcribe_manager

import (
	"time"
)

// Defines values for TranscribeDirection.
const (
	TranscribeDirectionBoth TranscribeDirection = "both"
	TranscribeDirectionIn   TranscribeDirection = "in"
	TranscribeDirectionOut  TranscribeDirection = "out"
)

// Defines values for TranscribeReferenceType.
const (
	TranscribereferenceTypeCall       TranscribeReferenceType = "call"
	TranscribereferenceTypeConfbridge TranscribeReferenceType = "confbridge"
	TranscribereferenceTypeRecording  TranscribeReferenceType = "recording"
	TranscribereferenceTypeUnknown    TranscribeReferenceType = "unknown"
)

// Defines values for TranscribeStatus.
const (
	TranscribeStatusDone        TranscribeStatus = "done"
	TranscribeStatusProgressing TranscribeStatus = "progressing"
)

// Defines values for TranscriptDirection.
const (
	TranscriptDirectionBoth TranscriptDirection = "both"
	TranscriptDirectionIn   TranscriptDirection = "in"
	TranscriptDirectionOut  TranscriptDirection = "out"
)

// Transcribe defines model for Transcribe.
type Transcribe struct {
	// CustomerId Customer ID
	CustomerId *string              `json:"customer_id,omitempty"`
	Direction  *TranscribeDirection `json:"direction,omitempty"`

	// Id Transcribe id
	Id *string `json:"id,omitempty"`

	// Language BCP47 type's language code.
	Language *string `json:"language,omitempty"`

	// ReferenceId Call/Conference/Recording's ID
	ReferenceId   *string                  `json:"reference_id,omitempty"`
	ReferenceType *TranscribeReferenceType `json:"reference_type,omitempty"`
	Status        *TranscribeStatus        `json:"status,omitempty"`

	// TmCreate Timestamp when created
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when deleted
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when updated
	TmUpdate *time.Time `json:"tm_update,omitempty"`
}

// TranscribeDirection defines model for TranscribeDirection.
type TranscribeDirection string

// TranscribeReferenceType defines model for TranscribeReferenceType.
type TranscribeReferenceType string

// TranscribeStatus defines model for TranscribeStatus.
type TranscribeStatus string

// Transcript defines model for Transcript.
type Transcript struct {
	Direction *TranscriptDirection `json:"direction,omitempty"`

	// Id Transcript ID
	Id *string `json:"id,omitempty"`

	// Message Transcript message
	Message *string `json:"message,omitempty"`

	// TmCreate Timestamp when created
	TmCreate *string `json:"tm_create,omitempty"`

	// TmTranscript Timestamp for the transcript
	TmTranscript *string `json:"tm_transcript,omitempty"`

	// TranscribeId Transcribe ID
	TranscribeId *string `json:"transcribe_id,omitempty"`
}

// TranscriptDirection defines model for TranscriptDirection.
type TranscriptDirection string
