// Package chat_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package chat_manager

import (
	"time"

	externalRef0 "testoapi/gens/models/agent_manager"
	externalRef1 "testoapi/gens/models/common"
)

// Defines values for ChatType.
const (
	ChatTypeGroup  ChatType = "group"
	ChatTypeNormal ChatType = "normal"
)

// Defines values for ChatroomType.
const (
	ChatroomTypeGroup   ChatroomType = "group"
	ChatroomTypeNormal  ChatroomType = "normal"
	ChatroomTypeUnknown ChatroomType = "unknown"
)

// Defines values for MediaType.
const (
	MediaTypeAddress MediaType = "address"
	MediaTypeAgent   MediaType = "agent"
	MediaTypeFile    MediaType = "file"
	MediaTypeLink    MediaType = "link"
)

// Defines values for MessagechatType.
const (
	MessagechatTypeNormal MessagechatType = "normal"
	MessagechatTypeSystem MessagechatType = "system"
)

// Defines values for MessagechatroomType.
const (
	MessagechatroomTypeNormal  MessagechatroomType = "normal"
	MessagechatroomTypeSystem  MessagechatroomType = "system"
	MessagechatroomTypeUnknown MessagechatroomType = ""
)

// Chat defines model for Chat.
type Chat struct {
	// CustomerId Resource's customer ID.
	CustomerId *string `json:"customer_id,omitempty"`

	// Detail Detailed information about the chat.
	Detail *string `json:"detail,omitempty"`

	// Id Resource identifier.
	Id *string `json:"id,omitempty"`

	// Name Name of the chat.
	Name *string `json:"name,omitempty"`

	// ParticipantIds List of participant IDs (agent IDs).
	ParticipantIds *[]string `json:"participant_ids,omitempty"`

	// RoomOwnerId Owned agent's ID.
	RoomOwnerId *string `json:"room_owner_id,omitempty"`

	// TmCreate Timestamp when the chat was created.
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the chat was deleted.
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the chat was last updated.
	TmUpdate *time.Time `json:"tm_update,omitempty"`

	// Type Type of the chat.
	Type *ChatType `json:"type,omitempty"`
}

// ChatType Type of the chat.
type ChatType string

// Chatroom defines model for Chatroom.
type Chatroom struct {
	// ChatId Associated chat ID.
	ChatId *string `json:"chat_id,omitempty"`

	// CustomerId Resource's customer ID.
	CustomerId *string `json:"customer_id,omitempty"`

	// Detail Detailed information about the chat room.
	Detail *string `json:"detail,omitempty"`

	// Id Resource identifier.
	Id *string `json:"id,omitempty"`

	// Name Name of the chat room.
	Name *string `json:"name,omitempty"`

	// OwnerId Resource's owner ID.
	OwnerId   *string `json:"owner_id,omitempty"`
	OwnerType *string `json:"owner_type,omitempty"`

	// ParticipantIds List of participant agent IDs.
	ParticipantIds *[]string `json:"participant_ids,omitempty"`

	// RoomOwnerId Chat room's owner agent ID.
	RoomOwnerId *string `json:"room_owner_id,omitempty"`

	// TmCreate Timestamp when the chat room was created.
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the chat room was deleted.
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the chat room was last updated.
	TmUpdate *time.Time `json:"tm_update,omitempty"`

	// Type Type of the chat room.
	Type *ChatroomType `json:"type,omitempty"`
}

// ChatroomType Type of the chat room.
type ChatroomType string

// Media defines model for Media.
type Media struct {
	// Address Contains source or destination detail info.
	Address *externalRef1.Address `json:"address,omitempty"`

	// Agent Represents an agent resource.
	Agent *externalRef0.Agent `json:"agent,omitempty"`

	// FileId Valid only if the type is `file`.
	FileId *string `json:"file_id,omitempty"`

	// LinkUrl Valid only if the type is `link`.
	LinkUrl *string `json:"link_url,omitempty"`

	// Type Type of the media content.
	Type *MediaType `json:"type,omitempty"`
}

// MediaType Type of the media content.
type MediaType string

// Messagechat defines model for Messagechat.
type Messagechat struct {
	// ChatId Associated chat ID.
	ChatId *string `json:"chat_id,omitempty"`

	// Id Unique identifier (inherited from commonidentity.Identity).
	Id *string `json:"id,omitempty"`

	// Medias List of associated media objects.
	Medias *[]Media `json:"medias,omitempty"`

	// Source Contains source or destination detail info.
	Source *externalRef1.Address `json:"source,omitempty"`

	// Text Text content of the message.
	Text *string `json:"text,omitempty"`

	// TmCreate Timestamp when the message chat was created.
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the message chat was deleted.
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the message chat was last updated.
	TmUpdate *time.Time `json:"tm_update,omitempty"`

	// Type Type of the message chat.
	Type *MessagechatType `json:"type,omitempty"`
}

// MessagechatType Type of the message chat.
type MessagechatType string

// Messagechatroom defines model for Messagechatroom.
type Messagechatroom struct {
	// ChatroomId Associated chat room ID.
	ChatroomId *string `json:"chatroom_id,omitempty"`

	// CustomerId Resource's customer ID.
	CustomerId *string `json:"customer_id,omitempty"`

	// Id Resource identifier.
	Id *string `json:"id,omitempty"`

	// Medias List of associated media objects.
	Medias *[]Media `json:"medias,omitempty"`

	// MessagechatId Associated message chat ID.
	MessagechatId *string `json:"messagechat_id,omitempty"`

	// OwnerId Resource's owner ID.
	OwnerId   *string `json:"owner_id,omitempty"`
	OwnerType *string `json:"owner_type,omitempty"`

	// Source Contains source or destination detail info.
	Source *externalRef1.Address `json:"source,omitempty"`

	// Text Text content of the message.
	Text *string `json:"text,omitempty"`

	// TmCreate Timestamp when the message chat room was created.
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the message chat room was deleted.
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the message chat room was last updated.
	TmUpdate *time.Time `json:"tm_update,omitempty"`

	// Type Type of the message in the chat room.
	Type *MessagechatroomType `json:"type,omitempty"`
}

// MessagechatroomType Type of the message in the chat room.
type MessagechatroomType string
