// Package queue_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package queue_manager

import (
	externalRef1 "testoapi/gens/models/flow_manager"
)

// Defines values for QueueRoutingMethod.
const (
	QueueRoutingMethodNone   QueueRoutingMethod = ""
	QueueRoutingMethodRandom QueueRoutingMethod = "random"
)

// Defines values for QueuecallStatus.
const (
	QueuecallStatusAbandoned  QueuecallStatus = "abandoned"
	QueuecallStatusConnecting QueuecallStatus = "connecting"
	QueuecallStatusDone       QueuecallStatus = "done"
	QueuecallStatusInitiating QueuecallStatus = "initiating"
	QueuecallStatusKicking    QueuecallStatus = "kicking"
	QueuecallStatusService    QueuecallStatus = "service"
	QueuecallStatusWaiting    QueuecallStatus = "waiting"
)

// Defines values for QueuecallreferenceType.
const (
	QueuecallreferenceTypeCall QueuecallreferenceType = "call"
)

// Queue defines model for Queue.
type Queue struct {
	CustomerId          *string             `json:"customer_id,omitempty"`
	Detail              *string             `json:"detail,omitempty"`
	Id                  *string             `json:"id,omitempty"`
	Name                *string             `json:"name,omitempty"`
	RoutingMethod       *QueueRoutingMethod `json:"routing_method,omitempty"`
	ServiceQueuecallIds *[]string           `json:"service_queuecall_ids,omitempty"`

	// ServiceTimeout Service queue timeout in milliseconds.
	ServiceTimeout *int      `json:"service_timeout,omitempty"`
	TagIds         *[]string `json:"tag_ids,omitempty"`
	TmCreate       *string   `json:"tm_create,omitempty"`
	TmDelete       *string   `json:"tm_delete,omitempty"`
	TmUpdate       *string   `json:"tm_update,omitempty"`

	// TotalAbandonedCount Total abandoned call count.
	TotalAbandonedCount *int `json:"total_abandoned_count,omitempty"`

	// TotalIncomingCount Total incoming call count.
	TotalIncomingCount *int `json:"total_incoming_count,omitempty"`

	// TotalServicedCount Total serviced call count.
	TotalServicedCount *int                   `json:"total_serviced_count,omitempty"`
	WaitActions        *[]externalRef1.Action `json:"wait_actions,omitempty"`
	WaitQueuecallIds   *[]string              `json:"wait_queuecall_ids,omitempty"`

	// WaitTimeout Wait queue timeout in milliseconds.
	WaitTimeout *int `json:"wait_timeout,omitempty"`
}

// QueueRoutingMethod defines model for QueueRoutingMethod.
type QueueRoutingMethod string

// Queuecall defines model for Queuecall.
type Queuecall struct {
	CustomerId *string `json:"customer_id,omitempty"`

	// DurationService Duration for service in milliseconds
	DurationService *int `json:"duration_service,omitempty"`

	// DurationWaiting Duration for waiting in milliseconds
	DurationWaiting *int                    `json:"duration_waiting,omitempty"`
	Id              *string                 `json:"id,omitempty"`
	ReferenceId     *string                 `json:"reference_id,omitempty"`
	ReferenceType   *QueuecallreferenceType `json:"reference_type,omitempty"`

	// ServiceAgentId The ID of the service agent handling the queue call
	ServiceAgentId *string          `json:"service_agent_id,omitempty"`
	Status         *QueuecallStatus `json:"status,omitempty"`

	// TmCreate Timestamp when the queue call was created
	TmCreate *string `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the queue call was deleted
	TmDelete *string `json:"tm_delete,omitempty"`

	// TmService Timestamp when the queue call started service
	TmService *string `json:"tm_service,omitempty"`

	// TmUpdate Timestamp when the queue call was last updated
	TmUpdate *string `json:"tm_update,omitempty"`
}

// QueuecallStatus defines model for QueuecallStatus.
type QueuecallStatus string

// QueuecallreferenceType defines model for Queuecallreference_type.
type QueuecallreferenceType string
