// Package campaign_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package campaign_manager

import (
	"time"

	externalRef0 "testoapi/gens/models/common"
)

// Defines values for CampaigncallResult.
const (
	CampaigncallResultFail    CampaigncallResult = "fail"
	CampaigncallResultNone    CampaigncallResult = ""
	CampaigncallResultSuccess CampaigncallResult = "success"
)

// Defines values for CampaigncallStatus.
const (
	CampaigncallStatusDialing     CampaigncallStatus = "dialing"
	CampaigncallStatusDone        CampaigncallStatus = "done"
	CampaigncallStatusProgressing CampaigncallStatus = "progressing"
)

// Defines values for CampaigncallreferenceType.
const (
	CampaigncallreferenceTypeCall CampaigncallreferenceType = "call"
	CampaigncallreferenceTypeFlow CampaigncallreferenceType = "flow"
	CampaigncallreferenceTypeNone CampaigncallreferenceType = "none"
)

// Campaigncall defines model for Campaigncall.
type Campaigncall struct {
	// ActiveflowId Identifier of the active flow.
	ActiveflowId *string `json:"activeflow_id,omitempty"`

	// CampaignId Identifier of the campaign.
	CampaignId *string `json:"campaign_id,omitempty"`

	// CustomerId Identifier of the customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Destination Contains source or destination detail info.
	Destination *externalRef0.Address `json:"destination,omitempty"`

	// DestinationIndex Index of the destination.
	DestinationIndex *int `json:"destination_index,omitempty"`

	// FlowId Identifier of the flow.
	FlowId *string `json:"flow_id,omitempty"`

	// Id Unique identifier of the campaign call.
	Id *string `json:"id,omitempty"`

	// OutdialId Identifier of the outbound dial.
	OutdialId *string `json:"outdial_id,omitempty"`

	// OutdialTargetId Identifier of the outbound dial target.
	OutdialTargetId *string `json:"outdial_target_id,omitempty"`

	// OutplanId Identifier of the outbound plan.
	OutplanId *string `json:"outplan_id,omitempty"`

	// QueueId Identifier of the queue.
	QueueId *string `json:"queue_id,omitempty"`

	// ReferenceId Identifier of the reference.
	ReferenceId   *string                    `json:"reference_id,omitempty"`
	ReferenceType *CampaigncallreferenceType `json:"reference_type,omitempty"`
	Result        *CampaigncallResult        `json:"result,omitempty"`

	// Source Contains source or destination detail info.
	Source *externalRef0.Address `json:"source,omitempty"`
	Status *CampaigncallStatus   `json:"status,omitempty"`

	// TmCreate Timestamp when the campaign call was created.
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the campaign call was deleted.
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the campaign call was last updated.
	TmUpdate *time.Time `json:"tm_update,omitempty"`

	// TryCount Number of dialing attempts.
	TryCount *int `json:"try_count,omitempty"`
}

// CampaigncallResult defines model for CampaigncallResult.
type CampaigncallResult string

// CampaigncallStatus defines model for CampaigncallStatus.
type CampaigncallStatus string

// CampaigncallreferenceType defines model for Campaigncallreference_type.
type CampaigncallreferenceType string

// Outplan defines model for Outplan.
type Outplan struct {
	// CustomerId Identifier of the customer.
	CustomerId *string `json:"customer_id,omitempty"`

	// Detail Detailed information about the outplan.
	Detail *string `json:"detail,omitempty"`

	// DialTimeout Dial timeout in milliseconds.
	DialTimeout *int `json:"dial_timeout,omitempty"`

	// Id Unique identifier of the outplan.
	Id *string `json:"id,omitempty"`

	// MaxTryCount0 Maximum number of tries for level 0.
	MaxTryCount0 *int `json:"max_try_count_0,omitempty"`

	// MaxTryCount1 Maximum number of tries for level 1.
	MaxTryCount1 *int `json:"max_try_count_1,omitempty"`

	// MaxTryCount2 Maximum number of tries for level 2.
	MaxTryCount2 *int `json:"max_try_count_2,omitempty"`

	// MaxTryCount3 Maximum number of tries for level 3.
	MaxTryCount3 *int `json:"max_try_count_3,omitempty"`

	// MaxTryCount4 Maximum number of tries for level 4.
	MaxTryCount4 *int `json:"max_try_count_4,omitempty"`

	// Name Name of the outplan.
	Name *string `json:"name,omitempty"`

	// Source Contains source or destination detail info.
	Source *externalRef0.Address `json:"source,omitempty"`

	// TmCreate Timestamp when the outplan was created.
	TmCreate *time.Time `json:"tm_create,omitempty"`

	// TmDelete Timestamp when the outplan was deleted.
	TmDelete *time.Time `json:"tm_delete,omitempty"`

	// TmUpdate Timestamp when the outplan was last updated.
	TmUpdate *time.Time `json:"tm_update,omitempty"`

	// TryInterval Interval between dialing attempts in milliseconds.
	TryInterval *int `json:"try_interval,omitempty"`
}
